### ISSUE TITLE
如果是将ue4ss MOD切换到c#loader, 是否有查找内存对象和patch指定函数的简单例子？

### ISSUE THREAD

**Issue by reece15** [czastack/B1CSharpLoader#1]
非常伟大的工作！这个项目将使很多ue4ss不能实现的功能成为可能，我已经预料到未来会有很多玩法类MOD的出现。

但是我翻阅了源代码和示例程序，我不太确定是否有findfirstof这类工具可以查找内存对象？是否有实际的简单列子代码可以提供，比如
1. 查找内存对象和调用对应方法（比如 wukong对象）；
2. patch b1类的指定函数（比如猴毛召唤）。

再次感谢作者，非常了不起的项目。非常期望能收到回复。

**Comment by czastack** [comment]
你好，很多UE的api都是有的，可以参考GameDll里面的内容，需要ilspy等工具，后续会补充一些常用的功能使用例子。目前loader在一些mod作者中内测，近期可能会发布。目前还在处理patch，因为发现harmony没有按预期工作。

**Comment by SnarkyGhost** [comment]
How to get the BlackMyth's API?Seems like it used a customized version by Gamescience.

**Comment by czastack** [comment]
@SnarkyGhost You can use dnSpy or ilSpy and open GameDll/BtlSvr.Main.dll to see API
