### ISSUE TITLE
没看懂怎么安装啊  , 需要自己新建路径吗

### ISSUE THREAD

**Issue by Super1Windcloud** [czastack/B1CSharpLoader#3]
![image](https://github.com/user-attachments/assets/4627bf0c-74a5-4a41-9ecd-5f3029471c6b)

**Comment by czastack** [comment]
你好，开发的话clone下来工程，打开解决方案编译，或者进入具体项目dotnet build就行了。安装成品的话，到n网下载压缩包解压到游戏目录即可。
